In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('nbastatspergame2017.csv')

In [5]:
df.tail()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PS/G
590,482,Cody Zeller\zelleco01,C,24,CHO,62,58,27.8,4.1,7.1,...,0.679,2.2,4.4,6.5,1.6,1.0,0.9,1.0,3.0,10.3
591,483,Tyler Zeller\zellety01,C,27,BOS,51,5,10.3,1.5,3.1,...,0.564,0.8,1.6,2.4,0.8,0.1,0.4,0.4,1.2,3.5
592,484,Stephen Zimmerman\zimmest01,C,20,ORL,19,0,5.7,0.5,1.6,...,0.600,0.6,1.3,1.8,0.2,0.1,0.3,0.2,0.9,1.2
593,485,Paul Zipser\zipsepa01,SF,22,CHI,44,18,19.2,2.0,5.0,...,0.775,0.3,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5
594,486,Ivica Zubac\zubaciv01,C,19,LAL,38,11,16.0,3.3,6.3,...,0.653,1.1,3.1,4.2,0.8,0.4,0.9,0.8,1.7,7.5

In [7]:
df.isnull().tail()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PS/G
590,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
591,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
592,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
593,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
594,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False